### ISSUE TITLE
Broken Under 19.2.3

### ISSUE THREAD

**Issue by Tailslide** [DevExpress-Examples/how-to-use-custom-appointment-fields-in-a-custom-editing-form-e2782#2]
I can't seem to compile or run this under devexpress 19.2.3 even after running through the upgrade process.  It's trying to access some private member of the EF class and after I make the method public I get a different error when it runs and tries to fill the table adapter.

**Comment by Tailslide** [comment]
Issue was not version of controls.. there are fields missing in the .mdb file I don't know how this ever worked.  Add Amount field of type decimal to Cars table and Amount field of type OLE Object to CarsScheduling table and it will run after making the method public.

**Comment by Tailslide** [comment]
https://github.com/Tailslide/how-to-use-custom-appointment-fields-in-a-custom-editing-form-e2782/blob/16fc6c41da64480427c0b714e0577d8364e4150a/CS/SimpleCustomFields/CarsDB.mdb

**Comment by AlexMedusa** [comment]
Hi,

Thank you for reaching out to us. I reproduced the issue on my side. We will update the example to avoid this error.
